version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  backend:
    build: .
    container_name: backend_container
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      PORT: 4000
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB_PREFIX: tenant_
      JWT_SECRET: mySecret
